name: Deploy to VM

on:
  workflow_run:
    workflows: [".NET CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VM
        run: |
          ssh ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
            docker pull jacbstpn/productapi:latest
            docker stop productapi || true
            docker rm productapi || true
            docker run -d -p 5000:8080 --name productapi jacbstpn/productapi:latest
          EOF